### PR TITLE
Jwplayer

### PR DESCRIPTION
**Pull request by efjacobson**

### CODE REVIEW

**Comment by efjacobson** [comment]
@gdbrown this is ready for another pass but cannot be finalized until schema updates are released

**Comment by efjacobson** [comment]
@gdbrown feeling good about this, although i do think we need a util to resolve artifact urls. something like

`jwplayerUrl($mezzanineRef, 'manifest')` but you could do it for the other types too so `jwplayerUrl($mezzanineRef, 'thumbnail_sprite')` and `jwplayerUrl($mezzanineRef, 'captions')` etc

**Comment by gdbrown** [comment]
@efjacobson agreed, like url provider in dam, something like that.

**Comment by efjacobson** [comment]
@gdbrown added `Triniti\OvpJwplayer\UrlProvider`, lmk what you think. would mirror this on the js side of course for apps

**Comment by efjacobson** [comment]
@gdbrown this is ready for another look, got all your feedback from this morning/last night

**Comment by efjacobson** [comment]
@gdbrown addressed your slack comments in recent commit

**Pull request merged**
